Repository wecode-bootcamp-korea/32-westagram-backend-3-team, pull requests merged in 2022-04, with the labels that each got.

#3 [최민석] Mission1 : Django 초기 세팅
  students/minseok/westagram/.gitignore
  students/minseok/westagram/manage.py
  students/minseok/westagram/requirements.txt
  students/minseok/westagram/westagram/__init__.py
  students/minseok/westagram/westagram/asgi.py
  students/minseok/westagram/westagram/settings.py
  students/minseok/westagram/westagram/urls.py
  students/minseok/westagram/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [임수연] Mission 1 : Django 초기 세팅
  students/sooyeon/.gitignore
  students/sooyeon/manage.py
  students/sooyeon/requirements.txt
  students/sooyeon/westagram/__init__.py
  students/sooyeon/westagram/asgi.py
  students/sooyeon/westagram/settings.py
  students/sooyeon/westagram/urls.py
  students/sooyeon/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#1 [김영빈] Mission1 : Django 초기 세팅
  students/youngbin/.gitignore
  students/youngbin/manage.py
  students/youngbin/requirements.txt
  students/youngbin/westagram/__init__.py
  students/youngbin/westagram/asgi.py
  students/youngbin/westagram/settings.py
  students/youngbin/westagram/urls.py
  students/youngbin/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#6 [안남규] Mission 1 : Django 초기 세팅 #32
  students/namkyu/.gitignore
  students/namkyu/manage.py
  students/namkyu/requirements.txt
  students/namkyu/westargram/__init__.py
  students/namkyu/westargram/asgi.py
  students/namkyu/westargram/settings.py
  students/namkyu/westargram/urls.py
  students/namkyu/westargram/wsgi.py
Labels: 멘토 리뷰 요청

#5 [김영빈] Mission2:모델링
  students/youngbin/users/__init__.py
  students/youngbin/users/admin.py
  students/youngbin/users/apps.py
  students/youngbin/users/migrations/__init__.py
  students/youngbin/users/models.py
  students/youngbin/users/tests.py
  students/youngbin/users/views.py
  students/youngbin/westagram/settings.py
Labels: 멘토 리뷰 요청, 수정 요청

#4 [임수연] Mission 2 : 모델링
  students/sooyeon/users/__init__.py
  students/sooyeon/users/admin.py
  students/sooyeon/users/apps.py
  students/sooyeon/users/migrations/__init__.py
  students/sooyeon/users/models.py
  students/sooyeon/users/tests.py
  students/sooyeon/users/views.py
  students/sooyeon/westagram/settings.py
Labels: 멘토 리뷰 요청, 수정 요청

#8 [안남규] Mission 2: 모델링
  students/namkyu/users/__init__.py
  students/namkyu/users/admin.py
  students/namkyu/users/apps.py
  students/namkyu/users/migrations/__init__.py
  students/namkyu/users/models.py
  students/namkyu/users/tests.py
  students/namkyu/users/views.py
  students/namkyu/westargram/settings.py
Labels: 멘토 리뷰 요청, 수정 요청

#13 [임수연] Mission 3 : 회원가입 기능 구현
  students/sooyeon/users/migrations/0001_initial.py
  students/sooyeon/users/urls.py
  students/sooyeon/users/validation.py
  students/sooyeon/users/views.py
  students/sooyeon/westagram/urls.py
Labels: 멘토 리뷰 요청

#14 [최민석] Mission 3: 회원가입 기능 구현
  students/minseok/westagram/users/urls.py
  students/minseok/westagram/users/validation.py
  students/minseok/westagram/users/views.py
  students/minseok/westagram/westagram/urls.py
Labels: 멘토 리뷰 요청

#12 [김영빈] Mission 3: 회원가입 기능 구현
  students/youngbin/users/admin.py
  students/youngbin/users/migrations/0001_initial.py
  students/youngbin/users/models.py
  students/youngbin/users/urls.py
  students/youngbin/users/validation.py
  students/youngbin/users/views.py
  students/youngbin/westagram/settings.py
  students/youngbin/westagram/urls.py
Labels: 멘토 리뷰 요청

#9 [김영빈] Mission 3: 회원가입 기능 구현
  students/youngbin/users/admin.py
  students/youngbin/users/migrations/0001_initial.py
  students/youngbin/users/models.py
  students/youngbin/users/urls.py
  students/youngbin/users/views.py
  students/youngbin/westagram/settings.py
  students/youngbin/westagram/urls.py
Labels: 수정 요청

#11 [안남규] Mission 3: 회원가입 기능 구현
  students/namkyu/manage.py
  students/namkyu/users/migrations/0001_initial.py
  students/namkyu/users/urls.py
  students/namkyu/users/views.py
  students/namkyu/westagram/__init__.py
  students/namkyu/westagram/asgi.py
  students/namkyu/westagram/settings.py
  students/namkyu/westagram/urls.py
  students/namkyu/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#15 [안남규] Mission 4 : 로그인 기능 구현
  students/namkyu/users/urls.py
  students/namkyu/users/views.py
Labels: 멘토 리뷰 요청, 수정 요청, 피어 리뷰 완료

#18 [임수연] Mission 4: 로그인 기능 구현
  students/sooyeon/users/urls.py
  students/sooyeon/users/validation.py
  students/sooyeon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#17 [최민석] Mission 4: 로그인 기능 구현
  students/minseok/westagram/users/urls.py
  students/minseok/westagram/users/validation.py
  students/minseok/westagram/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#16 [김영빈] Mission 4 : 로그인 기능 구현
  students/youngbin/users/urls.py
  students/youngbin/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#22 [김영빈] Mission 5: 회원가입 비밀번호 암호화 적용
  students/youngbin/requirements.txt
  students/youngbin/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#20 [임수연] Mission 5: 회원가입 비밀번호 암호화 적용
  students/sooyeon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#21 [최민석] Mission 5: 회원가입 비밀번호 암호화 적용
  students/minseok/westagram/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#19 [안남규] Mission 5: 회원가입 비밀번호 암호화 적용
  students/namkyu/users/models.py
  students/namkyu/users/views.py
Labels: 수정 요청, 피어 리뷰 완료
